### ISSUE TITLE
Java 17 record with type parameter throws: ArrayIndexOutOfBoundsException:  Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by Joofthan** [smallrye/smallrye-open-api#1004]
SmallRye Open API can not handle records with generic type parameters.

**Tested in**
Quarkus 2.6.0.CR1 and 2.5.3.Final with Java 17 on Windows 10

**Java Version**
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

**Description**
Using a record with generic type is working as expected in Quarkus 2.6.0.CR1.
After adding smallrye-open-api extension in pom.xml the application does not build anymore, with the Exception shown below.

```Java
@PUT
@Path("hello")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.TEXT_PLAIN)
 public String hello(MyRecord<UserEntity> myRecord) {
    return "Hello "+myRecord.content();
}
```

```Java
public record MyRecord<T>(T content) {
    
}
```

**Stacktrace / Exception**
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[ERROR]         at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4165)
[ERROR]         at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1347)
[ERROR]         at io.smallrye.openapi.runtime.scanner.dataobject.TypeResolver.buildParamTypeResolutionMap(TypeResolver.java:1045)
[ERROR]         at io.smallrye.openapi.runtime.scanner.dataobject.TypeResolver.getAllFields(TypeResolver.java:460)
[ERROR]         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.depthFirstGraphSearch(OpenApiDataObjectScanner.java:252)
[ERROR]         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:213)
[ERROR]         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:159)
[ERROR]         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.otherTypeToSchema(SchemaFactory.java:610)
[ERROR]         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.typeToSchema(SchemaFactory.java:448)
[ERROR]         at io.smallrye.openapi.runtime.scanner.spi.AnnotationScanner.processRequestBody(AnnotationScanner.java:881)
[ERROR]         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethod(JaxRsAnnotationScanner.java:435)
[ERROR]         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.lambda$processResourceMethods$0(JaxRsAnnotationScanner.java:277)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[ERROR]         at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[ERROR]         at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[ERROR]         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethods(JaxRsAnnotationScanner.java:275)
[ERROR]         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClass(JaxRsAnnotationScanner.java:245)
[ERROR]         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClasses(JaxRsAnnotationScanner.java:220)
[ERROR]         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.scan(JaxRsAnnotationScanner.java:152)
[ERROR]         at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:127)
[ERROR]         at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:718)
[ERROR]         at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:576)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)

**Example Application**
1. Clone  https://gitlab.com/jonidienste-bitbucket/quarkus-smallrye-error
2. mvn package
3. mvn quarkus:dev

Checking that the resource is working without smallrye-openapi:
1. remove smallrye-openapi dependency
2. mvn package
3. mvn quarkus:dev
4. `curl -X 'PUT'   'http://localhost:8080/hello/hello'   -H 'accept: text/plain'   -H 'Content-Type: application/json'   -d '{  "content": {    "name": "sd"  }}'`

**Comment by Joofthan** [comment]
The parameters in the error message are interchanged. Or the variable names are confusing:
https://github.com/smallrye/smallrye-open-api/blob/2a0f35fcd8c688660d6a228b93ec1cb8c86cab3a/core/src/main/java/io/smallrye/openapi/runtime/scanner/dataobject/DataObjectLogging.java#L88

Used here:
https://github.com/smallrye/smallrye-open-api/blob/2a0f35fcd8c688660d6a228b93ec1cb8c86cab3a/core/src/main/java/io/smallrye/openapi/runtime/scanner/dataobject/TypeResolver.java#L1048

**Comment by MikeEdgar** [comment]
This will require a fix in Jandex: https://github.com/wildfly/jandex/issues/160
