### ISSUE TITLE
No enum constant exception thrown in quarkus

### ISSUE THREAD

**Issue by suleymanozev** [smallrye/smallrye-open-api#1052]
2022-02-15 18:51:48,619 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-15) HTTP Request to /q/openapi failed, error id: d2921701-6599-4f86-b505-e33e12c0b909-2: java.lang.IllegalArgumentException: No enum constant org.eclipse.microprofile.openapi.models.media.Schema.SchemaType.STR?NG
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.eclipse.microprofile.openapi.models.media.Schema$SchemaType.valueOf(Schema.java:48)
	at io.smallrye.openapi.runtime.io.schema.SchemaReader.readSchemaType(SchemaReader.java:148)
	at io.smallrye.openapi.runtime.io.schema.SchemaReader.readSchema(SchemaReader.java:112)
	at io.smallrye.openapi.runtime.io.mediatype.MediaTypeReader.readMediaType(MediaTypeReader.java:67)
	at io.smallrye.openapi.runtime.io.content.ContentReader.readContent(ContentReader.java:78)
	at io.smallrye.openapi.runtime.io.response.ResponseReader.readResponse(ResponseReader.java:219)
	at io.smallrye.openapi.runtime.io.response.ResponseReader.readResponses(ResponseReader.java:93)
	at io.smallrye.openapi.runtime.io.operation.OperationReader.readOperation(OperationReader.java:98)
	at io.smallrye.openapi.runtime.io.paths.PathsReader.readPathItem(PathsReader.java:122)
	at io.smallrye.openapi.runtime.io.paths.PathsReader.readPaths(PathsReader.java:61)
	at io.smallrye.openapi.runtime.io.definition.DefinitionReader.processDefinition(DefinitionReader.java:82)
	at io.smallrye.openapi.runtime.io.OpenApiParser.parse(OpenApiParser.java:112)
	at io.smallrye.openapi.runtime.io.OpenApiParser.parse(OpenApiParser.java:79)
	at io.smallrye.openapi.runtime.OpenApiProcessor.modelFromStaticFile(OpenApiProcessor.java:101)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService$StaticDocument.<init>(OpenApiDocumentService.java:65)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService.<init>(OpenApiDocumentService.java:33)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Subclass.<init>(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.create(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:101)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:18)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.getDocument(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiHandler.handle(OpenApiHandler.java:82)
	at io.quarkus.smallrye.openapi.runtime.OpenApiHandler.handle(OpenApiHandler.java:19)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MikeEdgar** [comment]
@suleymanozev - what character encoding is used by your JVM?

**Comment by suleymanozev** [comment]
This problem may be in Turkish, but also in other non-English languages. I will send a pull request soon.

**Comment by MikeEdgar** [comment]
Perfect, thank you :+1:
