### ISSUE TITLE
`SchemaFactory` bound to Jackson

### ISSUE THREAD

**Issue by tjquinno** [smallrye/smallrye-open-api#1161]
The changes implementing enhancement #245 allow libraries layering on SmallRye OpenAPI to implement `AnnotationScannerExtension` in order to, among other things, provide their own parsing rather than Jackson.

One of our users seems to have found a spot where SmallRye is still tightly bound to Jackson. This happens to be in 2.1.16.

It looks as if adding `@Schema` to a field triggers this, in that the lambda in `SchemaFactory#parseSchemaAttr` invokes `JsonUtil#parseValue` which invokes Jackson.

Below is the relevant part of a stack trace.

Not sure if there might be other similar places in the code; I didn't see others in `SchemaFactory` but I didn't look beyond there.

```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.lambda$parseSchemaAttr$5(SchemaFactory.java:315)
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readAttr(SchemaFactory.java:343)
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.parseSchemaAttr(SchemaFactory.java:309)
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:180)
	at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.readSchemaAnnotatedField(AnnotationTargetProcessor.java:327)
	at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.processField(AnnotationTargetProcessor.java:163)
	at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.process(AnnotationTargetProcessor.java:65)
	at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.lambda$depthFirstGraphSearch$1(OpenApiDataObjectScanner.java:262)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.depthFirstGraphSearch(OpenApiDataObjectScanner.java:262)
	at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:213)
	at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:159)
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.introspectClassToSchema(SchemaFactory.java:527)
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.typeToSchema(SchemaFactory.java:444)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processClassSchemas$3(OpenApiAnnotationScanner.java:208)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processClassSchemas(OpenApiAnnotationScanner.java:208)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scanMicroProfileOpenApiAnnotations(OpenApiAnnotationScanner.java:153)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:118)
	at io.helidon.openapi.OpenAPISupport.lambda$expandModelUsingAnnotations$3(OpenAPISupport.java:364)
```

**Comment by phillip-kruger** [comment]
@tjquinno Are you working on a PR for this ?

**Comment by tjquinno** [comment]
@phillip-kruger No, I'm not. Too much to do on other things and not familiar enough with the SmallRye code base to be efficient.
