### ISSUE TITLE
java.lang.UnsupportedOperationException using @RolesAllowed and @SecurityRequirement

### ISSUE THREAD

**Issue by dometec** [smallrye/smallrye-open-api#1640]
While using @RolesAllowed and @SecurityRequirement in a Rest Endpoint:

```
@SecurityRequirement(name = "myrealm")
@RolesAllowed({ SecurityRoles.ADMINISTRATOR, SecurityRoles.APPMANAGER })
public class AppVersionsManagementRest {
```

I get this exception on boot:

```
Caused by: java.lang.UnsupportedOperationException
at java.base/java.util.AbstractList.add(AbstractList.java:153)
at java.base/java.util.AbstractList.add(AbstractList.java:111)
at io.smallrye.openapi.runtime.scanner.processor.JavaSecurityProcessor.addRolesAllowed(JavaSecurityProcessor.java:142)
at io.smallrye.openapi.runtime.scanner.processor.JavaSecurityProcessor.processSecurityRolesForMethodOperation(JavaSecurityProcessor.java:98)
at io.smallrye.openapi.runtime.scanner.processor.JavaSecurityProcessor.processSecurityRoles(JavaSecurityProcessor.java:39)
at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethod(JaxRsAnnotationScanner.java:493)
at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.lambda$processResourceMethods$0(JaxRsAnnotationScanner.java:289)
```

That is because when the @SecurityRequirement doesn't have any scope, addScheme uses an immutable collection here (L38):
https://github.com/smallrye/smallrye-open-api/blob/23842c0c95a937ba2bc1fc5e7789d636a7e8fbac/core/src/main/java/io/smallrye/openapi/api/models/security/SecurityRequirementImpl.java#L35-L42

But addRolesAllowed tries to add some role to it (L142):

https://github.com/smallrye/smallrye-open-api/blob/23842c0c95a937ba2bc1fc5e7789d636a7e8fbac/core/src/main/java/io/smallrye/openapi/runtime/scanner/processor/JavaSecurityProcessor.java#L135-L145

**Comment by phillip-kruger** [comment]
@dometec do you want to do a fix and submit a PR ?

**Comment by dometec** [comment]
Sure, I still need understand why role are added into scopes. I'll try to study the code and came back in a few days ;)

**Comment by MikeEdgar** [comment]
@dometec are you still planning to look into this one?

**Comment by MikeEdgar** [comment]
No problem, I'll take a look.
