### ISSUE TITLE
RESTEasy param annotations on fields or properties causing mayem

### ISSUE THREAD

**Issue by FroMage** [smallrye/smallrye-open-api#197]
I've added RESTEasy param annotations on fields and properties of my class:

```java
@Path("/test")
public class TestResource {

    @GET
    public String getTest() {
        return "TEST";
    }

    // make sure these don't break the build when fields
    @org.jboss.resteasy.annotations.jaxrs.PathParam
    String pathField;
    @org.jboss.resteasy.annotations.jaxrs.FormParam
    String formField;
    @org.jboss.resteasy.annotations.jaxrs.CookieParam
    String cookieField;
    @org.jboss.resteasy.annotations.jaxrs.HeaderParam
    String headerField;
    @org.jboss.resteasy.annotations.jaxrs.MatrixParam
    String matrixField;
    @org.jboss.resteasy.annotations.jaxrs.QueryParam
    String queryField;

    // make sure these don't break the build when properties
    public String getPathProperty() {
        return null;
    }

    @org.jboss.resteasy.annotations.jaxrs.PathParam
    public void setPathProperty(String p) {
    }

    public String getFormProperty() {
        return null;
    }

    @org.jboss.resteasy.annotations.jaxrs.FormParam
    public void setFormProperty(String p) {
    }

    public String getCookieProperty() {
        return null;
    }

    @org.jboss.resteasy.annotations.jaxrs.CookieParam
    public void setCookieProperty(String p) {
    }

    public String getHeaderProperty() {
        return null;
    }

    @org.jboss.resteasy.annotations.jaxrs.HeaderParam
    public void setHeaderProperty(String p) {
    }

    public String getMatrixProperty() {
        return null;
    }

    @org.jboss.resteasy.annotations.jaxrs.MatrixParam
    public void setMatrixProperty(String p) {
    }

    public String getQueryProperty() {
        return null;
    }

    @org.jboss.resteasy.annotations.jaxrs.QueryParam
    public void setQueryProperty(String p) {
    }

}
```

And the generated documentation became a bit crazy:

```
  "/test{testMatrix}": {
    "get": {
      "responses": {
        "200": {
          "description": "OK",
          "content": {
            "*/*": {
              "schema": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "parameters": [
      {
        "name": "p",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "pathField",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "testMatrix",
        "in": "path",
        "required": true,
        "schema": {
          "type": "object",
          "properties": {
            "p": {
              "type": "string"
            },
            "matrixField": {
              "type": "string"
            }
          }
        },
        "style": "matrix"
      },
      {
        "name": "p",
        "in": "query",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "queryField",
        "in": "query",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "headerField",
        "in": "header",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "p",
        "in": "header",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "cookieField",
        "in": "cookie",
        "schema": {
          "type": "string"
        }
      },
      {
        "name": "p",
        "in": "cookie",
        "schema": {
          "type": "string"
        }
      }
    ]
  },
```

Several issues here:

- It's using the setter property's parameter name instead of the property name: `p` should be `cookieProperty`
- If I put the annotation on the getter by mistake, I get an NPE:
```
Caused by: java.lang.NullPointerException
	at io.smallrye.openapi.runtime.util.SchemaFactory.typeToSchema(SchemaFactory.java:230)
	at io.smallrye.openapi.runtime.scanner.ParameterProcessor.setSchemaProperties(ParameterProcessor.java:612)
	at io.smallrye.openapi.runtime.scanner.ParameterProcessor.getParameters(ParameterProcessor.java:486)
	at io.smallrye.openapi.runtime.scanner.ParameterProcessor.process(ParameterProcessor.java:352)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:584)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsResourceClass(OpenApiAnnotationScanner.java:437)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:214)
```
- What's with the `testMatrix` name? Where did it come from? It should be either `matrixField` or `matrixProperty`, and what is it doing in the URI?
- Why do I get `"parameters"` sometimes inside `get` and sometimes after it as a sibling? This is allowed?

**Comment by MikeEdgar** [comment]
@FroMage ,

1. I agree that the setter methods annotated with params should use the method name rather than the parameter (`cookieProperty` vs `p`). I'll look into a fix.
2. Needs research, but I think this scenario should be ignored by the run time. That is, nothing should be generated - assuming RESTEasy does nothing here also.
3. The `testMatrix` name is a generated parameter name for a Matrix that applies to the `/test` path segment. In this case it includes two elements, `p` and `matrixField`. Per #1, it should only contain `matrixField` based on the field name and the setter property name. The generated name is only to link the parameter inserted into the path and the named entry in the `parameters` list. Matrix parameters are properties of an implied object that is defined for a segment of the path.
4. Parameters declared as method arguments will nest under the HTTP method, whereas parameters declared in the class apply to all of the methods for the `@Path` of the resource class. This is valid OpenAPI - [see here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathItemObject).

**Comment by MikeEdgar** [comment]
After some additional review, I believe the matrix parameter processing was incorrectly implemented and my description in point 3 is not correct.

**Comment by FroMage** [comment]
> Needs research, but I think this scenario should be ignored by the run time. That is, nothing should be generated - assuming RESTEasy does nothing here also.

This is about the NPE, right? RESTEasy will ignore the annotation since it's on the wrong element. But it should not crash ;)

Additional note about matrix, when I have a matrix param as method parameter I don't think it ends up in the path, which is also why I was confused by those suddenly popping up.

**Comment by FroMage** [comment]
Thanks.
