### ISSUE TITLE
Quarkus & SmallRyeOpenApiProcessor with NPE

### ISSUE THREAD

**Issue by nirodg** [smallrye/smallrye-open-api#237]
**Describe the bug**
I have an interface which defines basic CRUD operations for APIs (custom library). 
Additionally I have defined a `List<Object> getAll` which is making the Quarkus to crash
[Link to the interface (github)](https://github.com/nirodg/dodo/blob/develop/runtime/src/main/java/ro/brage/dodo/http/rs/RestApi.java)

**Expected behavior**
Application deployed and being able to call the endpoint

**Actual behavior**
A NPE ocures

**To Reproduce**
1.  Define own endpoint and extend `RestApi.java` ([Link howTo](https://github.com/nirodg/dodo/#the-api))
2.  Try to run app with quarkus
3.  NPE occures

**Environment**
 - Output of `uname -a` or `ver`: 

```MINGW64_NT-10.0 dorin-xps 2.10.0(0.325/5/3) 2018-07-25 13:06 x86_64 Msys```

 - Output of `java -version`: 
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
 - Quarkus version or git rev: `1.1.0.Final`

**Additional context**

Seems like if the service returns a `List<?>` the processor will end up in NPE.
I've tried to use the `Response` instead and it works. 
```
    @GET
    @Path("/")
    public Response getAll() throws Exception {
        List<ENTITY> data = service.getAll();
        return Response.ok(mapper.findDTOs(data)).build(); 
    }
``` 

Some similar issue https://github.com/smallrye/smallrye-open-api/issues/230

**Comment by MikeEdgar** [comment]
@nirodg - can you post the stack trace?

**Comment by nirodg** [comment]
> @nirodg - can you post the stack trace?

Right, I totally forgot about the stack trace

```
0:00:13,270 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
10:00:13,415 INFO  [org.hib.jpa.boo.int.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
10:00:13,519 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - javax.ws.rs.core.SecurityContext
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
10:00:13,520 INFO  [org.hib.Version] HHH000412: Hibernate Core {5.4.9.Final}
10:00:13,748 INFO  [io.qua.arc.pro.BeanProcessor] Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field ro.brage.dodo.http.rs.RestApiService#mapper,
        - @Inject field ro.brage.dodo.http.rs.RestApiService#service,
        - @Inject field ro.brage.dodo.jpa.EntityService#entityManager,
        - @PostConstruct callback ro.brage.dodo.jpa.EntityService#initialize(),
        - @Inject field ro.brage.dodo.http.rs.RestApiService#mapper,
        - @Inject field ro.brage.dodo.http.rs.RestApiService#service,
        - @Inject field ro.brage.dodo.http.rs.RestApiService#mapper,
        - @Inject field ro.brage.dodo.http.rs.RestApiService#service,
        - @Inject field ro.brage.dodo.jpa.EntityService#entityManager,
        - @PostConstruct callback ro.brage.dodo.jpa.EntityService#initialize(),
        - @Inject field ro.brage.dodo.jpa.EntityService#entityManager,
        - @PostConstruct callback ro.brage.dodo.jpa.EntityService#initialize()
10:00:13,777 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors

        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.NullPointerException
        at io.smallrye.openapi.runtime.util.TypeUtil.isTerminalType(TypeUtil.java:396)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.resolveTypeVariable(TypeProcessor.java:239)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.resolveParameterizedType(TypeProcessor.java:214)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.readParameterizedType(TypeProcessor.java:180)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.processType(TypeProcessor.java:133)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.processField(AnnotationTargetProcessor.java:151)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.process(AnnotationTargetProcessor.java:89)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.preProcessSpecial(OpenApiDataObjectScanner.java:274)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.resolveSpecial(OpenApiDataObjectScanner.java:270)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:208)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:163)
        at io.smallrye.openapi.runtime.util.SchemaFactory.typeToSchema(SchemaFactory.java:360)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.createResponseFromJaxRsMethod(OpenApiAnnotationScanner.java:924)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:688)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:422)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsResourceClass(OpenApiAnnotationScanner.java:420)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:221)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:298)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:157)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.NullPointerException
        at io.smallrye.openapi.runtime.util.TypeUtil.isTerminalType(TypeUtil.java:396)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.resolveTypeVariable(TypeProcessor.java:239)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.resolveParameterizedType(TypeProcessor.java:214)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.readParameterizedType(TypeProcessor.java:180)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.processType(TypeProcessor.java:133)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.processField(AnnotationTargetProcessor.java:151)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.process(AnnotationTargetProcessor.java:89)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.preProcessSpecial(OpenApiDataObjectScanner.java:274)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.resolveSpecial(OpenApiDataObjectScanner.java:270)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:208)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:163)
        at io.smallrye.openapi.runtime.util.SchemaFactory.typeToSchema(SchemaFactory.java:360)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.createResponseFromJaxRsMethod(OpenApiAnnotationScanner.java:924)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:688)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:422)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsResourceClass(OpenApiAnnotationScanner.java:420)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:221)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:298)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

        at io.quarkus.builder.Execution.run(Execution.java:108)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:130)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:111)
        ... 3 more
Caused by: java.lang.NullPointerException
        at io.smallrye.openapi.runtime.util.TypeUtil.isTerminalType(TypeUtil.java:396)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.resolveTypeVariable(TypeProcessor.java:239)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.resolveParameterizedType(TypeProcessor.java:214)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.readParameterizedType(TypeProcessor.java:180)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.processType(TypeProcessor.java:133)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.processField(AnnotationTargetProcessor.java:151)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.process(AnnotationTargetProcessor.java:89)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.preProcessSpecial(OpenApiDataObjectScanner.java:274)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.resolveSpecial(OpenApiDataObjectScanner.java:270)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:208)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:163)
        at io.smallrye.openapi.runtime.util.SchemaFactory.typeToSchema(SchemaFactory.java:360)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.createResponseFromJaxRsMethod(OpenApiAnnotationScanner.java:924)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:688)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:422)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsResourceClass(OpenApiAnnotationScanner.java:420)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:221)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:298)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

10:00:13,799 INFO  [io.qua.dev.DevModeMain] Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
```

**Comment by MikeEdgar** [comment]
@nirodg - thanks. It appears that the problem is related to the use of a generic collection where the scanner is unable to determine the type of the collection type parameter (e.g. `ENTITY` in `List<ENTITY>` and it is not falling back to `object`. Would you mind to push a simple project to Github that demonstrates the class hierarchy being used?

**Comment by nirodg** [comment]
> @nirodg - thanks. It appears that the problem is related to the use of a generic collection where the scanner is unable to determine the type of the collection type parameter (e.g. `ENTITY` in `List<ENTITY>` and it is not falling back to `object`. Would you mind to push a simple project to Github that demonstrates the class hierarchy being used?

I see. I do have an example project where its shown how to use the library - I will soon update it due to the changes I've done in the lib, but it does give a clear idea. 

Here is the definition of the API endpoint https://github.com/nirodg/dodo-example/blob/develop/src/main/java/com/brage/dodo/example/rs/api/CarRestService.java

Here the implementation and where all injections occurs
https://github.com/nirodg/dodo-example/blob/develop/src/main/java/com/brage/dodo/example/rs/services/CarRestServiceBean.java

Currently I'm porting my library to Quarkus and I'm wandering if it a problem of getting properly the generics via reflection or a problem due to the open-api lib.

**Comment by MikeEdgar** [comment]
> problem of getting properly the generics via reflection or a problem due to the open-api lib

The stack trace you posted is certainly a problem with the annotation scanner.

> PS. If needed I can quickly setup a quarkus project with the exact implementation so the NPE happens.

That would definitely help in debugging this.

**Comment by nirodg** [comment]
@MikeEdgar Okay, so please follow the following steps in order to reproduce it

1. `git clone git@github.com:nirodg/dodo.git && git checkout open-api && mvn clean install` 
2. `git clone git@github.com:nirodg/code-with-quarkus-dodo.git`
3. `./mvnw clean compile quarkus:dev` 

Notes: 

- `DummyRestEndpoint` defines the endpoint and extends basic CRUD operations
- Removing the `quarkus-smallrye-openapi` dependency the Quarkus app boots fine
- The `dodo` lib needs a loots of polishing so it can be ported to Quarkus, yet it works

**Comment by zyc** [comment]
I'm facing the same problem exactly when using generic types. Take a look at my JSON data structure:

```
package rest.data

interface ReqData<in E> {

    fun escreverEm(entidade: E)
}
```

```
package rest.data

import core.entity.TipoDespesa
import java.util.*
import javax.validation.constraints.NotNull

class IdReqData : ReqData<TipoDespesa> {

    @NotNull
    lateinit var id: UUID

    override fun escreverEm(entidade: TipoDespesa) {
        entidade.id = id
    }
}
```

```
package rest.data

import core.entity.UsuarioPagamento
import java.math.BigDecimal
import javax.validation.Valid
import javax.validation.constraints.NotNull

class UsuarioPagamentoReqData : ReqData<UsuarioPagamento> {

    @NotNull
    lateinit var valor: BigDecimal

    @Valid
    @NotNull
    lateinit var usuario: IdReqData

    override fun escreverEm(entidade: UsuarioPagamento) {
        entidade.valor = valor
    }
}
```

```
package rest.data

import core.entity.Coordenada
import java.math.BigDecimal
import javax.validation.constraints.NotNull

class CoordenadaReqData : ReqData<Coordenada> {

    @NotNull
    lateinit var latitude: BigDecimal

    @NotNull
    lateinit var longitude: BigDecimal

    override fun escreverEm(entidade: Coordenada) {
        entidade.latitude = latitude
        entidade.longitude = longitude
    }
}
```

```
package rest.data

import core.entity.Coordenada
import core.entity.Pagamento
import java.time.LocalDate
import javax.validation.Valid
import javax.validation.constraints.NotEmpty
import javax.validation.constraints.NotNull

abstract class PagamentoReqData<in E : Pagamento<*>> : ReqData<E> {

    @NotNull
    lateinit var data: LocalDate

    @Valid
    var coordenada: CoordenadaReqData? = null

    @Valid
    @NotNull
    lateinit var tipo: IdReqData

    @Valid
    @NotEmpty
    lateinit var valores: List<UsuarioPagamentoReqData>

    override fun escreverEm(entidade: E) {
        entidade.data = data

        if (entidade.coordenada == null) {
            entidade.coordenada = Coordenada()
        }

        coordenada?.escreverEm(entidade.coordenada!!)
    }
}
```

**Comment by MikeEdgar** [comment]
Hi @zyc - can you also share your endpoint class which has the `@Path` annotations? That should help confirm whether your issue is caused by the same thing.
