### ISSUE TITLE
OPENIDCONNECT is not recognised as security scheme

### ISSUE THREAD

**Issue by gintsgints** [smallrye/smallrye-open-api#240]
When I specify two security schemes:
```
@SecuritySchemes(value = {
        @SecurityScheme(securitySchemeName = "api_key",
            type = SecuritySchemeType.APIKEY,
            apiKeyName = "api_key",
            in = SecuritySchemeIn.HEADER),
        @SecurityScheme(securitySchemeName = "openIdConnectUrl",
                type = SecuritySchemeType.OPENIDCONNECT,
                openIdConnectUrl = "http://localhost:8280/auth/realms/quarkus/.well-known/openid-configuration")}
)
```
Only api_key scheme is recognised.
If I leave openidconnect scheme alone, I get stack trace:
```
java.lang.NullPointerException
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.saveSecurityScheme(OpenApiAnnotationScanner.java:296)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.checkSecurityScheme(OpenApiAnnotationScanner.java:273)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:216)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:300)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.base/java.lang.Thread.run(Thread.java:830)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Resulted in: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.NullPointerException
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.saveSecurityScheme(OpenApiAnnotationScanner.java:296)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.checkSecurityScheme(OpenApiAnnotationScanner.java:273)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:216)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:300)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.base/java.lang.Thread.run(Thread.java:830)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

	at io.quarkus.builder.Execution.run(Execution.java:108)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:128)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:113)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:208)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:136)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:51)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:43)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Resulted in: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.NullPointerException
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.saveSecurityScheme(OpenApiAnnotationScanner.java:296)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.checkSecurityScheme(OpenApiAnnotationScanner.java:273)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:216)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:300)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.base/java.lang.Thread.run(Thread.java:830)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:180)
	... 10 more
```

**Comment by MikeEdgar** [comment]
@gintsgints - thanks for opening this. I see why the `NullPointerException` is thrown, but can you provide some more details around your configuration where having two `@SecurityScheme`s results in the `APIKEY` scheme missing in the output? I tried to reproduce that behavior by placing the `@SecuritySchemes` on the JAX-RS `Application` class, but both schemes are in the output. Where are you placing the `@SecuritySchemes` annotation that you gave above?

**Comment by gintsgints** [comment]
I create it in quarkus App. - https://github.com/gintsgints/quarkus-ws
It is said, that quarkus do not need Application class, but for purpose of annotations it shoud be created.

**Comment by gintsgints** [comment]
Interesting, but this happens over another implementation - https://github.com/gintsgints/spring-kotlin-ws

**Comment by MikeEdgar** [comment]
@gintsgints , using the quarkus-ws app you linked I see both schemes in the output. This is not what you see yourself?

```yaml
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
    openIdConnectUrl:
      type: openIdConnect
      openIdConnectUrl: http://localhost:8280/auth/realms/quarkus/.well-known/openid-configuration
```

Note that the `securitySchemeName` of `openIdConnectUrl` does not align with `@SecurityRequirement(name = "openId")` in `UsersResource`. You probably also intend for `UsersResource$User` to be a `static` class to avoid the `this$0` property in the output.

**Comment by gintsgints** [comment]
Ohhh. I see both in generated document. But only one is available at swagger-ui. 

Seems like this is a problem of swagger-ui.

**Comment by gintsgints** [comment]
https://swagger.io/docs/specification/authentication/openid-connect-discovery/

```
Swagger UI
OIDC is currently not supported in Swagger Editor and Swagger UI. Please follow this issue for updates.
```

**Comment by StephenOTT** [comment]
for future ref: `Support for OpenID Connect Discovery was added in Swagger UI v. 3.38.0 and Swagger Editor 3.14.8.`

from https://swagger.io/docs/specification/authentication/openid-connect-discovery/

**Comment by phillip-kruger** [comment]
Hi @StephenOTT - OIDC is supported in Quarkus. Are you having some issue ?
