### ISSUE TITLE
NPE in OpenApiAnnotationScanner.createResponseFromJaxRsMethod

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-open-api#248]
Using a very simple JAX-RS resource that returns a JSON-P object, SmallRye OpenAPI throws a NPE:

```java
@Path("/")
public class HelloResource {
    @GET
    public JsonObject hello() {
        return Json.createObjectBuilder()
                .add("content", "foobar")
                .build();
    }
}
```

```
2020-01-30 19:06:44,774 ERROR [stderr] (main) Caused by: java.lang.NullPointerException
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.createResponseFromJaxRsMethod(OpenApiAnnotationScanner.java:934)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:688)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:422)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
2020-01-30 19:06:44,775 ERROR [stderr] (main)   at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsResourceClass(OpenApiAnnotationScanner.java:420)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:221)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at io.smallrye.openapi.runtime.OpenApiProcessor.modelFromAnnotations(OpenApiProcessor.java:72)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at org.wildfly.swarm.microprofile.openapi.runtime.OpenApiDeploymentProcessor.process(OpenApiDeploymentProcessor.java:101)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at org.wildfly.swarm.microprofile.openapi.runtime.OpenApiDeploymentProcessor$Proxy$_$$_WeldClientProxy.process(Unknown Source)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:233)
2020-01-30 19:06:44,776 ERROR [stderr] (main)   ... 12 more
```

As you can see in the stacktrace, this is using Thorntail. Specifically, Thorntail 2.6.0.Final, which uses SmallRye OpenAPI 1.1.20. I've tried to rebuild Thorntail with SmallRye OpenAPI 1.1.10, that works well. I've also tried to build SmallRye OpenAPI `master` branch and integrate that into Thorntail, same error.

I'm attaching a simple Thorntail-based reproducer.

[reproducer.zip](https://github.com/smallrye/smallrye-open-api/files/4135632/reproducer.zip)

**Comment by MikeEdgar** [comment]
@Ladicek , I wasn't able to reproduce this. Are there any other variables besides what is listed below? The following steps:
```
curl -L -O https://github.com/smallrye/smallrye-open-api/files/4135632/reproducer.zip
unzip reproducer.zip
cd reproducer/
mvn thorntail:run
curl http://127.0.0.1:8080/openapi
```
Produce this output:
```yaml
---
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /:
    get:
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: object
```

**Comment by Ladicek** [comment]
Aaah, sorry about that, totally forgot to include instructions for reproducing. If you do `mvn thorntail:run -Dthorntail.useUberJar` (or `mvn clean package && java -jar target/openapi-reproducer-thorntail.jar`), you will see the error.

But that suggests there's probably something wrong on Thorntail side, of course...

But then, NPE is always a bug :-)

I will look more into it on our side.

**Comment by MikeEdgar** [comment]
@Ladicek - it looks like `JsonObject` is not on the class path at scan time. I agree the NPE is a problem.
