### ISSUE TITLE
Got UnsupportedOperationException if methods of OASFilter return null

### ISSUE THREAD

**Issue by code-d** [smallrye/smallrye-open-api#502]
Got UnsupportedOperationException if methods of custom `org.eclipse.microprofile.openapi.OASFilter` impl return `null`

```
[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableMap.remove(Collections.java:1460)
	at io.smallrye.openapi.api.util.FilterUtil.filterSchemas(FilterUtil.java:443)
	at io.smallrye.openapi.api.util.FilterUtil.filterComponents(FilterUtil.java:67)
	at io.smallrye.openapi.api.util.FilterUtil.applyFilter(FilterUtil.java:45)
	at io.smallrye.openapi.api.OpenApiDocument.filterModel(OpenApiDocument.java:168)
	at io.smallrye.openapi.api.OpenApiDocument.initialize(OpenApiDocument.java:128)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.loadDocument(SmallRyeOpenApiProcessor.java:471)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:282)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

`io.smallrye.openapi.api.util.FilterUtil` class has bug

**Comment by phillip-kruger** [comment]
Hi @code-d . Thanks for the issue. So are you trying to remove something from the generated Model ? Or why is the filter returning null ? Can you post a small reproducer ?

**Comment by MikeEdgar** [comment]
I took a quick look at this one and I think it's because some places in `FilterUtil` are operating directly on the `Map`s returned from the OpenAPI interfaces. For example, `filterCallbacks` removes from the map of callbacks, but instead should be using `Components#removeCallback` (or whatever the other parent model is based on context, since each method may be called from several locations in the utility). Returning `null` from a filter method is the signal to remove it from the containing model.

https://github.com/smallrye/smallrye-open-api/blob/9045653974167773cd3b7c7432d519e1cc52c252/core/src/main/java/io/smallrye/openapi/api/util/FilterUtil.java#L78-L89

**Comment by phillip-kruger** [comment]
Thanks @MikeEdgar - that sounds fixable.

**Comment by MikeEdgar** [comment]
> @MikeEdgar - are you looking at this ?

@phillip-kruger I haven't started anything yet. I might not have time until late this week.
