### ISSUE TITLE
OpenApiDataObjectScanner throws ArrayIndexOutOfBoundsException while mapping a generic with 2 Parameters 

### ISSUE THREAD

**Issue by malkochoglu** [smallrye/smallrye-open-api#910]
Hi,
I am trying to return [io.vavr.control.Either<L,R>](https://www.javadoc.io/doc/io.vavr/vavr/0.9.2/io/vavr/control/Either.html) in a REST endpoint on Quarkus. Class Either<L,R> has an iterable super interface. Thus, OpenApiDataObjectScanner picks Iterable<E>. That causes a mismatch and process fails with java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1. 
TIA...

Version: Quarkus 2.2.2.Final
Dependency: io.quarkus:quarkus-smallrye-openapi
Build tool: Gradle

`Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1321)
	at io.smallrye.openapi.runtime.scanner.dataobject.TypeResolver.buildParamTypeResolutionMap(TypeResolver.java:1025)
	at io.smallrye.openapi.runtime.scanner.dataobject.TypeResolver.getAllFields(TypeResolver.java:460)
	at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.resolveSpecial(OpenApiDataObjectScanner.java:319)
	at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:206)
	at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:157)
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.otherTypeToSchema(SchemaFactory.java:582)
	at io.smallrye.openapi.runtime.io.schema.SchemaFactory.typeToSchema(SchemaFactory.java:428)
	at io.smallrye.openapi.runtime.scanner.spi.AnnotationScanner.createResponseFromRestMethod(AnnotationScanner.java:414)
	at io.smallrye.openapi.runtime.scanner.spi.AnnotationScanner.processResponse(AnnotationScanner.java:346)
	at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethod(JaxRsAnnotationScanner.java:435)
	at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.lambda$processResourceMethods$0(JaxRsAnnotationScanner.java:271)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethods(JaxRsAnnotationScanner.java:269)
	at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClass(JaxRsAnnotationScanner.java:239)
	at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClasses(JaxRsAnnotationScanner.java:214)
	at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.scan(JaxRsAnnotationScanner.java:146)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:127)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateAnnotationModel(SmallRyeOpenApiProcessor.java:452)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:320)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)`

**Comment by MikeEdgar** [comment]
Hi @malkochoglu , what is the expected schema for an `io.vavr.control.Either`? I'm curious if You've tried specifying a schema some other way.

**Comment by MikeEdgar** [comment]
Would a possible work-around be to provide a response schema with `anyOf`?
```java
@GET
@Path("/either")
@Produces({ "text/plain" })
@APIResponse(content = @Content(schema = @Schema(anyOf = { Integer.class, String.class })))
public io.vavr.control.Either<Integer, String> getEither() {
    return null;
}
```

**Comment by malkochoglu** [comment]
@MikeEdgar thx for looking into this.  No I haven't provided a Schema definition. The work around you provided helped to eliminate the exception. However, it does not align to what I get as API response. Let me tell you my observation as a vavr newbie. 
There is a jackson data type add on (vavr-jackson). Using that add on, what I get as a json response is below:
`[
    "right",
    "2464e197-d1eb-4ac4-8596-7ef5bec3a1e7"
]` 

So when using vavr-jackson, Either object is always mapped to an array of objects. First element is of String type one of "right" or "left". (Right->success, Left->Error). Second object is of either first or second generics type based on error and success (left/right). So for this case then below should be better and objectscanner does not throw the exception:
`    @APIResponse(content = @Content(schema = @Schema(type = SchemaType.ARRAY, implementation = String.class)))
`

**Comment by MikeEdgar** [comment]
Thanks @malkochoglu . I have some changes I'm looking at locally to fix the NPE and coincidentally it will produce your expected result of an array of "right".
