### ISSUE TITLE
Kotlin Continuations should be excluded from requestBody

### ISSUE THREAD

**Issue by rgmz** [smallrye/smallrye-open-api#969]
_Cross-posting this from:_ https://github.com/quarkusio/quarkus/issues/21509

This appears to relate to #893. It should be possible to fix by filtering `kotlin.coroutines.Continuation` from `requestBody`. I'm happy to create a PR, if someone can point me in the right direction. :)

**Comment by MikeEdgar** [comment]
@rgmz - thank you. If you can dig in and see why the code change in #920 isn't working for this case, that would help a lot. You should be able to add a new test case similar to the one added in that PR that adjusts the endpoint to match the Java-equivalent of the Kotlin endpoint.

**Comment by rgmz** [comment]
@MikeEdgar: I opened #970 to troubleshoot this. The schema generates as expected in the tests, so I'll need to dig deeper to figure out what's going on...

**Comment by MikeEdgar** [comment]
There's a reason why the Jax-RS extension doesn't show up in the dep tree. @phillip-kruger, can you remind me again?

**Comment by phillip-kruger** [comment]
Maybe for testing ? I am not sure

**Comment by MikeEdgar** [comment]
It may be because it's only used by the Quarkus internals during the scan and it's not actually depended on for the project to compile or run. Something along those lines...

**Comment by rgmz** [comment]
I can troubleshoot the [Quarkus extension](https://github.com/quarkusio/quarkus/tree/main/extensions/smallrye-openapi) and add some tests. Any pointers on where to get started?

For example: what are the functions of the [`deployment`](https://github.com/quarkusio/quarkus/tree/main/extensions/smallrye-openapi/deployment), [`runtime`](https://github.com/quarkusio/quarkus/tree/main/extensions/smallrye-openapi/runtime), and  [`spi`](https://github.com/quarkusio/quarkus/tree/main/extensions/smallrye-openapi/spi) modules? Which one should I be looking into?

**Comment by rgmz** [comment]
I _think_ I'm on the right track, but I'm unable to run the tests due to a confusing error.

```sh
$ ./mvnw test -f extensions/smallrye-openapi/deployment/ -Dtest=OpenApiPathWithSegmentsTestCase
...
Caused by: java.lang.ClassCastException: class io.quarkus.test.common.http.TestHTTPConfigSourceProvider cannot be cast to class org.eclipse.microprofile.config.spi.ConfigSourceProvider (io.quarkus.test.common.http.TestHTTPConfigSourceProvider is in unnamed module of loader 'app'; org.eclipse.microprofile.config.spi.ConfigSourceProvider is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @5faeeb56)
        at io.quarkus.runtime.configuration.RuntimeConfigSourceProvider.getConfigSources(RuntimeConfigSourceProvider.java:20)
        at io.quarkus.runtime.configuration.ConfigUtils.addSourceProvider(ConfigUtils.java:192)
        at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1012)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:261)
        ... 49 more

```

https://github.com/rgmz/quarkus/tree/fix/smallrye-openapi/kotlin-continuations
